2023-05-15 18:58:59,188 - freqtrade.loggers - INFO - Verbosity set to 0
2023-05-15 18:58:59,189 - freqtrade.configuration.configuration - INFO - Runmode set to live.
2023-05-15 18:58:59,191 - freqtrade.configuration.configuration - INFO - Parameter --db-url detected ...
2023-05-15 18:58:59,192 - freqtrade.configuration.configuration - INFO - Dry run is disabled
2023-05-15 18:58:59,193 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:////freqtrade/user_data/tradesv3_freqtrade2.sqlite"
2023-05-15 18:58:59,195 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 10 ...
2023-05-15 18:58:59,299 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2023-05-15 18:58:59,302 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binance ...
2023-05-15 18:58:59,304 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2023-05-15 18:58:59,320 - freqtrade.exchange.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2023-05-15 18:58:59,322 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2023-05-15 18:58:59,424 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy keltnerhopt from '/freqtrade/user_data/strategies/keltnerchannel-rsi.py'...
2023-05-15 18:58:59,426 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2023-05-15 18:58:59,428 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2023-05-15 18:58:59,429 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: unlimited.
2023-05-15 18:58:59,430 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}.
2023-05-15 18:58:59,432 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'max_open_trades' with value in config file: 10.
2023-05-15 18:58:59,433 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 100}
2023-05-15 18:58:59,434 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 1d
2023-05-15 18:58:59,435 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.3
2023-05-15 18:58:59,436 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2023-05-15 18:58:59,437 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2023-05-15 18:58:59,438 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2023-05-15 18:58:59,439 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2023-05-15 18:58:59,441 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2023-05-15 18:58:59,442 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'limit', 'exit': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False, 'stoploss_on_exchange_interval': 60}
2023-05-15 18:58:59,443 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'GTC', 'exit': 'GTC'}
2023-05-15 18:58:59,444 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2023-05-15 18:58:59,445 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: unlimited
2023-05-15 18:58:59,446 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2023-05-15 18:58:59,447 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 0
2023-05-15 18:58:59,448 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}
2023-05-15 18:58:59,449 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
2023-05-15 18:58:59,450 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
2023-05-15 18:58:59,451 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: False
2023-05-15 18:58:59,452 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0
2023-05-15 18:58:59,453 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2023-05-15 18:58:59,454 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2023-05-15 18:58:59,455 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2023-05-15 18:58:59,457 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2023-05-15 18:58:59,458 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_open_trades: 10
2023-05-15 18:58:59,459 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2023-05-15 18:58:59,466 - freqtrade.exchange.exchange - INFO - Using CCXT 3.0.37
2023-05-15 18:58:59,502 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2023-05-15 18:59:09,660 - freqtrade.exchange.exchange - ERROR - Unable to initialize markets.
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
TimeoutError: _ssl.c:980: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/home/ftuser/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.binance.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 599, in fetch
    response = self.session.request(
  File "/home/ftuser/.local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ftuser/.local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/ftuser/.local/lib/python3.10/site-packages/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.binance.com', port=443): Read timed out. (read timeout=10)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/exchange.py", line 485, in _load_markets
    self._markets = self._api.load_markets(params={})
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 1457, in load_markets
    currencies = self.fetch_currencies()
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/binance.py", line 1625, in fetch_currencies
    response = self.sapiGetCapitalConfigGetall(params)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 505, in inner
    return entry(_self, **inner_kwargs)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/binance.py", line 6923, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2929, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 629, in fetch
    raise RequestTimeout(details) from e
ccxt.base.errors.RequestTimeout: binance GET https://api.binance.com/sapi/v1/capital/config/getall?timestamp=1684177139503&recvWindow=10000&signature=2eeb190956a54d8a962196e62c879d81c4295495b707235659889fed99c83502
2023-05-15 18:59:09,666 - freqtrade.commands.trade_commands - ERROR - Could not load markets, therefore cannot start. Please investigate the above error for more details.
2023-05-15 18:59:09,668 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 24, in start_trading
    worker = Worker(args)
  File "/freqtrade/freqtrade/worker.py", line 37, in __init__
    self._init(False)
  File "/freqtrade/freqtrade/worker.py", line 53, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/freqtrade/freqtrade/freqtradebot.py", line 70, in __init__
    self.exchange = ExchangeResolver.load_exchange(
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 34, in load_exchange
    exchange = ExchangeResolver._load_exchange(
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 60, in _load_exchange
    exchange = ex_class(**kwargs)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 185, in __init__
    self.validate_config(config)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 218, in validate_config
    self.validate_stakecurrency(config['stake_currency'])
  File "/freqtrade/freqtrade/exchange/exchange.py", line 520, in validate_stakecurrency
    raise OperationalException(
freqtrade.exceptions.OperationalException: Could not load markets, therefore cannot start. Please investigate the above error for more details.
2023-05-15 18:59:14,783 - freqtrade.loggers - INFO - Verbosity set to 0
2023-05-15 18:59:14,784 - freqtrade.configuration.configuration - INFO - Runmode set to live.
2023-05-15 18:59:14,785 - freqtrade.configuration.configuration - INFO - Parameter --db-url detected ...
2023-05-15 18:59:14,786 - freqtrade.configuration.configuration - INFO - Dry run is disabled
2023-05-15 18:59:14,787 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:////freqtrade/user_data/tradesv3_freqtrade2.sqlite"
2023-05-15 18:59:14,788 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 10 ...
2023-05-15 18:59:14,887 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2023-05-15 18:59:14,890 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binance ...
2023-05-15 18:59:14,892 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2023-05-15 18:59:14,908 - freqtrade.exchange.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2023-05-15 18:59:14,909 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2023-05-15 18:59:14,994 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy keltnerhopt from '/freqtrade/user_data/strategies/keltnerchannel-rsi.py'...
2023-05-15 18:59:14,997 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2023-05-15 18:59:14,998 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2023-05-15 18:59:15,000 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: unlimited.
2023-05-15 18:59:15,001 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}.
2023-05-15 18:59:15,002 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'max_open_trades' with value in config file: 10.
2023-05-15 18:59:15,004 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 100}
2023-05-15 18:59:15,005 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 1d
2023-05-15 18:59:15,006 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.3
2023-05-15 18:59:15,008 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2023-05-15 18:59:15,009 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2023-05-15 18:59:15,010 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2023-05-15 18:59:15,011 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2023-05-15 18:59:15,012 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2023-05-15 18:59:15,013 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'limit', 'exit': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False, 'stoploss_on_exchange_interval': 60}
2023-05-15 18:59:15,015 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'GTC', 'exit': 'GTC'}
2023-05-15 18:59:15,016 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2023-05-15 18:59:15,017 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: unlimited
2023-05-15 18:59:15,018 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2023-05-15 18:59:15,019 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 0
2023-05-15 18:59:15,020 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}
2023-05-15 18:59:15,021 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
2023-05-15 18:59:15,022 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
2023-05-15 18:59:15,023 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: False
2023-05-15 18:59:15,024 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0
2023-05-15 18:59:15,025 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2023-05-15 18:59:15,027 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2023-05-15 18:59:15,028 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2023-05-15 18:59:15,029 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2023-05-15 18:59:15,030 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_open_trades: 10
2023-05-15 18:59:15,032 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2023-05-15 18:59:15,039 - freqtrade.exchange.exchange - INFO - Using CCXT 3.0.37
2023-05-15 18:59:15,068 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2023-05-15 18:59:15,494 - freqtrade.exchange.exchange - ERROR - Unable to initialize markets.
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 625, in fetch
    response.raise_for_status()
  File "/home/ftuser/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error:  for url: https://api.binance.com/sapi/v1/capital/config/getall?timestamp=1684177155069&recvWindow=10000&signature=639a1721fb72f03b0bc308cfc105801e84b441db76d636952ffb6d108857cec4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/exchange.py", line 485, in _load_markets
    self._markets = self._api.load_markets(params={})
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 1457, in load_markets
    currencies = self.fetch_currencies()
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/binance.py", line 1625, in fetch_currencies
    response = self.sapiGetCapitalConfigGetall(params)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 505, in inner
    return entry(_self, **inner_kwargs)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/binance.py", line 6923, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2929, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 641, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/binance.py", line 6901, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 3238, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.AuthenticationError: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}
2023-05-15 18:59:15,500 - freqtrade.commands.trade_commands - ERROR - Could not load markets, therefore cannot start. Please investigate the above error for more details.
2023-05-15 18:59:15,501 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 24, in start_trading
    worker = Worker(args)
  File "/freqtrade/freqtrade/worker.py", line 37, in __init__
    self._init(False)
  File "/freqtrade/freqtrade/worker.py", line 53, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/freqtrade/freqtrade/freqtradebot.py", line 70, in __init__
    self.exchange = ExchangeResolver.load_exchange(
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 34, in load_exchange
    exchange = ExchangeResolver._load_exchange(
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 60, in _load_exchange
    exchange = ex_class(**kwargs)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 185, in __init__
    self.validate_config(config)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 218, in validate_config
    self.validate_stakecurrency(config['stake_currency'])
  File "/freqtrade/freqtrade/exchange/exchange.py", line 520, in validate_stakecurrency
    raise OperationalException(
freqtrade.exceptions.OperationalException: Could not load markets, therefore cannot start. Please investigate the above error for more details.
2023-05-15 18:59:20,688 - freqtrade.loggers - INFO - Verbosity set to 0
2023-05-15 18:59:20,689 - freqtrade.configuration.configuration - INFO - Runmode set to live.
2023-05-15 18:59:20,691 - freqtrade.configuration.configuration - INFO - Parameter --db-url detected ...
2023-05-15 18:59:20,692 - freqtrade.configuration.configuration - INFO - Dry run is disabled
2023-05-15 18:59:20,694 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:////freqtrade/user_data/tradesv3_freqtrade2.sqlite"
2023-05-15 18:59:20,694 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 10 ...
2023-05-15 18:59:20,789 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2023-05-15 18:59:20,791 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binance ...
2023-05-15 18:59:20,793 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2023-05-15 18:59:20,808 - freqtrade.exchange.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2023-05-15 18:59:20,809 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2023-05-15 18:59:20,895 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy keltnerhopt from '/freqtrade/user_data/strategies/keltnerchannel-rsi.py'...
2023-05-15 18:59:20,896 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2023-05-15 18:59:20,898 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2023-05-15 18:59:20,898 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: unlimited.
2023-05-15 18:59:20,899 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}.
2023-05-15 18:59:20,900 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'max_open_trades' with value in config file: 10.
2023-05-15 18:59:20,901 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 100}
2023-05-15 18:59:20,902 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 1d
2023-05-15 18:59:20,902 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.3
2023-05-15 18:59:20,903 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2023-05-15 18:59:20,904 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2023-05-15 18:59:20,905 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2023-05-15 18:59:20,906 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2023-05-15 18:59:20,906 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2023-05-15 18:59:20,907 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'limit', 'exit': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False, 'stoploss_on_exchange_interval': 60}
2023-05-15 18:59:20,908 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'GTC', 'exit': 'GTC'}
2023-05-15 18:59:20,909 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2023-05-15 18:59:20,910 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: unlimited
2023-05-15 18:59:20,910 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2023-05-15 18:59:20,911 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 0
2023-05-15 18:59:20,912 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}
2023-05-15 18:59:20,913 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
2023-05-15 18:59:20,913 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
2023-05-15 18:59:20,914 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: False
2023-05-15 18:59:20,915 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0
2023-05-15 18:59:20,916 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2023-05-15 18:59:20,916 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2023-05-15 18:59:20,917 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2023-05-15 18:59:20,918 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2023-05-15 18:59:20,919 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_open_trades: 10
2023-05-15 18:59:20,919 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2023-05-15 18:59:20,925 - freqtrade.exchange.exchange - INFO - Using CCXT 3.0.37
2023-05-15 18:59:20,953 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2023-05-15 18:59:21,297 - freqtrade.exchange.exchange - ERROR - Unable to initialize markets.
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 625, in fetch
    response.raise_for_status()
  File "/home/ftuser/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error:  for url: https://api.binance.com/sapi/v1/capital/config/getall?timestamp=1684177160954&recvWindow=10000&signature=bc7c989f2ae7242ac7d7b69526411d0e12744794b1402cf5cd5813eb39409911

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/exchange.py", line 485, in _load_markets
    self._markets = self._api.load_markets(params={})
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 1457, in load_markets
    currencies = self.fetch_currencies()
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/binance.py", line 1625, in fetch_currencies
    response = self.sapiGetCapitalConfigGetall(params)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 505, in inner
    return entry(_self, **inner_kwargs)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/binance.py", line 6923, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2929, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 641, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/binance.py", line 6901, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 3238, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.AuthenticationError: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}
2023-05-15 18:59:21,301 - freqtrade.commands.trade_commands - ERROR - Could not load markets, therefore cannot start. Please investigate the above error for more details.
2023-05-15 18:59:21,302 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 24, in start_trading
    worker = Worker(args)
  File "/freqtrade/freqtrade/worker.py", line 37, in __init__
    self._init(False)
  File "/freqtrade/freqtrade/worker.py", line 53, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/freqtrade/freqtrade/freqtradebot.py", line 70, in __init__
    self.exchange = ExchangeResolver.load_exchange(
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 34, in load_exchange
    exchange = ExchangeResolver._load_exchange(
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 60, in _load_exchange
    exchange = ex_class(**kwargs)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 185, in __init__
    self.validate_config(config)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 218, in validate_config
    self.validate_stakecurrency(config['stake_currency'])
  File "/freqtrade/freqtrade/exchange/exchange.py", line 520, in validate_stakecurrency
    raise OperationalException(
freqtrade.exceptions.OperationalException: Could not load markets, therefore cannot start. Please investigate the above error for more details.
